spring:
  application:
    name: kafka-to-postgres

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: postgres-saver-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.kafkapp.model.Event

  datasource:
    url: jdbc:postgresql://postgres:5432/kafkadb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

server:
  port: 8080